CREATE TABLE RUOLI
(
    ID SERIAL PRIMARY KEY,
    RUOLO_DESC VARCHAR(200) NOT NULL
);

INSERT INTO RUOLI (ID, RUOLO_DESC) VALUES (1, 'root'), (2, 'tutor'), (3, 'user');

CREATE TABLE Utenti
(
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(200) NOT NULL,
    PASSWORD VARCHAR(255) NULL,
    PRIVILEGI INT NOT NULL,
    CONSTRAINT Utenti_RUOLI_ID_fk FOREIGN KEY (PRIVILEGI) REFERENCES RUOLI (ID)
);

CREATE TABLE Tutor
(
    ID INT NULL,
    NOME VARCHAR(200) NULL,
    COGNOME VARCHAR(200) NULL,
    MAIL VARCHAR(200) NULL,
    ID_TUTOR SERIAL PRIMARY KEY,
    CONSTRAINT Tutor_Utenti_ID_fk FOREIGN KEY (ID) REFERENCES Utenti (ID)
);

CREATE TABLE Discente
(
    ID_DISCENTE SERIAL PRIMARY KEY,
    NOME VARCHAR(200) NOT NULL,
    COGNOME VARCHAR(200) NOT NULL,
    ID INT NULL,
    CONSTRAINT Discente_Utenti_ID_fk FOREIGN KEY (ID) REFERENCES Utenti (ID)
);

CREATE TABLE Materie
(
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(200) NOT NULL,
    TUTOR_ID INT NULL,
    PREZZO INT NULL,
    CONSTRAINT Materie_Tutor_ID_TUTOR_fk FOREIGN KEY (TUTOR_ID) REFERENCES Tutor (ID_TUTOR)
);

CREATE TABLE Lezioni
(
    ID_LEZ SERIAL PRIMARY KEY,
    ID_TUTOR INT NULL,
    ID_DISCENTE INT NULL,
    ID_MATERIA INT NULL,
    CONSTRAINT Lezioni_Discente_ID_DISCENTE_fk FOREIGN KEY (ID_DISCENTE) REFERENCES Discente (ID_DISCENTE),
    CONSTRAINT Lezioni_Materie_ID_fk FOREIGN KEY (ID_MATERIA) REFERENCES Materie (ID),
    CONSTRAINT Lezioni_Tutor_ID_TUTOR_fk FOREIGN KEY (ID_TUTOR) REFERENCES Tutor (ID_TUTOR)
);
